/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author trang
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private final Librarian admin = new Librarian(rootPane);
    
    public AdminForm() {
        initComponents();
        refresh(admin.getAllLibrarians());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLib = new javax.swing.JTable();
        jPanelTool = new javax.swing.JPanel();
        jPanelInput = new javax.swing.JPanel();
        jLabelID = new javax.swing.JLabel();
        jTextFieldLibID = new javax.swing.JTextField();
        jLabelFname = new javax.swing.JLabel();
        jTextFieldLibFname = new javax.swing.JTextField();
        jLabelLname = new javax.swing.JLabel();
        jTextFieldLibLname = new javax.swing.JTextField();
        jLabelUname = new javax.swing.JLabel();
        jTextFieldLibUsername = new javax.swing.JTextField();
        jLabelPasswd = new javax.swing.JLabel();
        jTextFieldLibPassword = new javax.swing.JTextField();
        jPanelButton = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jPanelTitle = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin - Manage Librarians");

        jPanelMain.setLayout(new java.awt.GridLayout(1, 2, 30, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jTableLib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLib.setForeground(new java.awt.Color(0, 18, 91));
        jTableLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First name", "Last name", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLib.setGridColor(new java.awt.Color(0, 18, 91));
        jTableLib.setRowHeight(30);
        jTableLib.setRowMargin(2);
        jTableLib.setSelectionBackground(new java.awt.Color(0, 18, 91));
        jTableLib.getTableHeader().setReorderingAllowed(false);
        jTableLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLibMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLib);

        jPanelMain.add(jScrollPane1);

        jPanelInput.setLayout(new java.awt.GridLayout(5, 2, 10, 7));

        jLabelID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelID.setForeground(new java.awt.Color(0, 18, 91));
        jLabelID.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelID.setText("ID:");
        jPanelInput.add(jLabelID);

        jTextFieldLibID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLibID.setForeground(new java.awt.Color(0, 18, 91));
        jTextFieldLibID.setBorder(null);
        jPanelInput.add(jTextFieldLibID);

        jLabelFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelFname.setForeground(new java.awt.Color(0, 18, 91));
        jLabelFname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelFname.setText("First name:");
        jPanelInput.add(jLabelFname);

        jTextFieldLibFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLibFname.setForeground(new java.awt.Color(0, 18, 91));
        jTextFieldLibFname.setBorder(null);
        jPanelInput.add(jTextFieldLibFname);

        jLabelLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelLname.setForeground(new java.awt.Color(0, 18, 91));
        jLabelLname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelLname.setText("Last name:");
        jPanelInput.add(jLabelLname);

        jTextFieldLibLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLibLname.setForeground(new java.awt.Color(0, 18, 91));
        jTextFieldLibLname.setBorder(null);
        jPanelInput.add(jTextFieldLibLname);

        jLabelUname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelUname.setForeground(new java.awt.Color(0, 18, 91));
        jLabelUname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelUname.setText("Username:");
        jPanelInput.add(jLabelUname);

        jTextFieldLibUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLibUsername.setForeground(new java.awt.Color(0, 18, 91));
        jTextFieldLibUsername.setBorder(null);
        jPanelInput.add(jTextFieldLibUsername);

        jLabelPasswd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPasswd.setForeground(new java.awt.Color(0, 18, 91));
        jLabelPasswd.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelPasswd.setText("Password:");
        jPanelInput.add(jLabelPasswd);

        jTextFieldLibPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldLibPassword.setForeground(new java.awt.Color(0, 18, 91));
        jTextFieldLibPassword.setBorder(null);
        jPanelInput.add(jTextFieldLibPassword);

        jPanelButton.setLayout(new java.awt.GridLayout(3, 1, 50, 20));

        jButtonClear.setBackground(new java.awt.Color(0, 18, 91));
        jButtonClear.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("Clear & Refresh");
        jButtonClear.setBorder(null);
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonClear);

        jButtonSearch.setBackground(new java.awt.Color(0, 18, 91));
        jButtonSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSearch.setText("Search");
        jButtonSearch.setBorder(null);
        jButtonSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });
        jPanelButton.add(jButtonSearch);

        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 20, 0));

        jButtonAdd.setBackground(new java.awt.Color(0, 18, 91));
        jButtonAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdd.setText("Add");
        jButtonAdd.setBorder(null);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAdd);

        jButtonUpdate.setBackground(new java.awt.Color(0, 18, 91));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.setBorder(null);
        jButtonUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonUpdate);

        jButtonDelete.setBackground(new java.awt.Color(0, 18, 91));
        jButtonDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Delete");
        jButtonDelete.setBorder(null);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDelete);

        jPanelButton.add(jPanel2);

        jLabelInfo.setText("<html>You are managing Librarians. \n<br>Make sure you know what you are performing. \n<br>From here, you can:\n<br>- Search for librarians by id, first name, last name and username\n<br>- Add new librarians\n<br>- Delete librarian by id\n<br>- Update librarian information</html>");

        javax.swing.GroupLayout jPanelToolLayout = new javax.swing.GroupLayout(jPanelTool);
        jPanelTool.setLayout(jPanelToolLayout);
        jPanelToolLayout.setHorizontalGroup(
            jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addComponent(jPanelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelToolLayout.setVerticalGroup(
            jPanelToolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelToolLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelMain.add(jPanelTool);

        jPanelTitle.setBackground(new java.awt.Color(0, 18, 91));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Manage Librarians");
        jPanelTitle.add(jLabel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String fname = jTextFieldLibFname.getText();
        String lname = jTextFieldLibLname.getText();
        String username = jTextFieldLibUsername.getText();
        String password = jTextFieldLibPassword.getText();
        
        if (fname.isBlank() || lname.isBlank() || username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(rootPane, "Fields required: First name, Last name, Username, Password", "Empty Field", JOptionPane.WARNING_MESSAGE);
        } else {
            if (admin.addLibrarian(fname, lname, username, password)) {
                JOptionPane.showMessageDialog(rootPane, username+" added successfully!", "Librarian Added", JOptionPane.INFORMATION_MESSAGE);
                refresh(admin.getAllLibrarians());
            } else {
                JOptionPane.showMessageDialog(rootPane, username + " not added", "Add Error", JOptionPane.ERROR_MESSAGE);
            }
            
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        refresh(admin.getAllLibrarians());
        JOptionPane.showMessageDialog(rootPane, "System refreshed", "Refresed", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            int id = Integer.valueOf(jTextFieldLibID.getText());
            int ok = JOptionPane.showConfirmDialog(rootPane, "Delete Librarian " + jTextFieldLibID.getText()+"?", "Delete Confirm", JOptionPane.OK_CANCEL_OPTION);
            if (ok == JOptionPane.OK_OPTION) {
                if (admin.deleteLibrarianByID(id)) {
                    JOptionPane.showMessageDialog(rootPane, jTextFieldLibID.getText() + " deleted", "Librarian Deleted", JOptionPane.INFORMATION_MESSAGE);
                    refresh(admin.getAllLibrarians());
                } else {
                    JOptionPane.showMessageDialog(rootPane, jTextFieldLibID.getText() + " deleted. Ensure ID is correct.", "Delete Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Enter number only for ID", "ID Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        try {
            int id = Integer.valueOf(jTextFieldLibID.getText());
            String fname = jTextFieldLibFname.getText();
            String lname = jTextFieldLibLname.getText();
            String username = jTextFieldLibUsername.getText();
            String password = jTextFieldLibPassword.getText();
            
            if (fname.isBlank() || lname.isBlank() || username.isBlank() || password.isBlank()) {
                JOptionPane.showMessageDialog(rootPane, "Enter all fields to update", "Empty Field", JOptionPane.WARNING_MESSAGE);
            } else {
                if (admin.updateLibrarianByID(id, fname, lname, username, password)) {
                    JOptionPane.showMessageDialog(rootPane, jTextFieldLibID.getText() + " updated", "Librarian Deleted", JOptionPane.INFORMATION_MESSAGE);
                    refresh(admin.getAllLibrarians());
                } else {
                        JOptionPane.showMessageDialog(rootPane, jTextFieldLibID.getText() + " not updated. Ensure ID is correct.", "Delete Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Input number only for ID", "ID Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        String fname = jTextFieldLibFname.getText();
        String lname = jTextFieldLibLname.getText();
        String username = jTextFieldLibUsername.getText();
        int id = -1;

        try {
            id = Integer.valueOf(jTextFieldLibID.getText());
        } catch (NumberFormatException ex) {
            if (fname.isBlank() && lname.isBlank() && username.isBlank()) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + " - Input number only for ID. You can search by ID, First name, Last name, Username.", "ID Invalid", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        DefaultTableModel model = admin.searchLibrarian(id, fname, lname, username);
        if (model != null) {
            refresh(model);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cannot search for Librarians. Please try again.", "Search Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTableLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLibMouseClicked
        // Get jTable model
        DefaultTableModel model = (DefaultTableModel)jTableLib.getModel();
        // Get selected row
        int rIndex = jTableLib.getSelectedRow();
        // Display data
        jTextFieldLibID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldLibFname.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldLibLname.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldLibUsername.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldLibPassword.setText(model.getValueAt(rIndex, 4).toString());
    }//GEN-LAST:event_jTableLibMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }
    
    private void refresh(DefaultTableModel table) {
        jTextFieldLibID.setText("");
        jTextFieldLibFname.setText("");
        jTextFieldLibLname.setText("");
        jTextFieldLibUsername.setText("");
        jTextFieldLibPassword.setText("");
        jTableLib.setModel(table);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFname;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelLname;
    private javax.swing.JLabel jLabelPasswd;
    private javax.swing.JLabel jLabelUname;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelButton;
    private javax.swing.JPanel jPanelInput;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPanel jPanelTool;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLib;
    private javax.swing.JTextField jTextFieldLibFname;
    private javax.swing.JTextField jTextFieldLibID;
    private javax.swing.JTextField jTextFieldLibLname;
    private javax.swing.JTextField jTextFieldLibPassword;
    private javax.swing.JTextField jTextFieldLibUsername;
    // End of variables declaration//GEN-END:variables
}
