/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

/**
 *
 * @author trang
 */
public class LibrarianForm extends javax.swing.JFrame {

    /**
     * Creates new form Librarian
     */
    public LibrarianForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBook = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLib = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldBookID = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBookTitle = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldBookAuthor = new javax.swing.JTextField();
        jTextFieldBookQuantity = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldBookAvailable = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButtonBookAdd = new javax.swing.JButton();
        jButtonBookClearFields = new javax.swing.JButton();
        jButtonBookDelete = new javax.swing.JButton();
        jButtonBookUpdate = new javax.swing.JButton();
        jButtonBookSearch = new javax.swing.JButton();
        jLabelBookInfo = new javax.swing.JLabel();
        jPanelReader = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLib1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldReaderID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldReaderFname = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldReaderLname = new javax.swing.JTextField();
        jButtonReaderAdd = new javax.swing.JButton();
        jButtonReaderClearField = new javax.swing.JButton();
        jButtonReaderDelete = new javax.swing.JButton();
        jButtonReaderUpdate = new javax.swing.JButton();
        jButtonReaderSearch = new javax.swing.JButton();
        jLabelReaderInfo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBook.setBackground(new java.awt.Color(255, 255, 255));

        jTableLib.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLib.setForeground(new java.awt.Color(0, 18, 91));
        jTableLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Fisrt author", "Quantity", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLib.setGridColor(new java.awt.Color(0, 18, 91));
        jTableLib.setSelectionBackground(new java.awt.Color(0, 18, 91));
        jScrollPane1.setViewportView(jTableLib);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 18, 91));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("ID:");

        jTextFieldBookID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookID.setForeground(new java.awt.Color(0, 18, 91));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 18, 91));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Title:");

        jTextFieldBookTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookTitle.setForeground(new java.awt.Color(0, 18, 91));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 18, 91));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("First author:");

        jTextFieldBookAuthor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookAuthor.setForeground(new java.awt.Color(0, 18, 91));

        jTextFieldBookQuantity.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookQuantity.setForeground(new java.awt.Color(0, 18, 91));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 18, 91));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Quantity:");

        jTextFieldBookAvailable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldBookAvailable.setForeground(new java.awt.Color(0, 18, 91));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 18, 91));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Available:");

        jButtonBookAdd.setBackground(new java.awt.Color(0, 18, 91));
        jButtonBookAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookAdd.setText("Add");
        jButtonBookAdd.setBorder(null);
        jButtonBookAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookAddActionPerformed(evt);
            }
        });

        jButtonBookClearFields.setBackground(new java.awt.Color(0, 18, 91));
        jButtonBookClearFields.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookClearFields.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookClearFields.setText("Clear Fields");
        jButtonBookClearFields.setBorder(null);
        jButtonBookClearFields.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookClearFieldsActionPerformed(evt);
            }
        });

        jButtonBookDelete.setBackground(new java.awt.Color(0, 18, 91));
        jButtonBookDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookDelete.setText("Delete");
        jButtonBookDelete.setBorder(null);
        jButtonBookDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookDeleteActionPerformed(evt);
            }
        });

        jButtonBookUpdate.setBackground(new java.awt.Color(0, 18, 91));
        jButtonBookUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookUpdate.setText("Update");
        jButtonBookUpdate.setBorder(null);
        jButtonBookUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookUpdateActionPerformed(evt);
            }
        });

        jButtonBookSearch.setBackground(new java.awt.Color(0, 18, 91));
        jButtonBookSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonBookSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonBookSearch.setText("Search");
        jButtonBookSearch.setBorder(null);
        jButtonBookSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonBookSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookSearchActionPerformed(evt);
            }
        });

        jLabelBookInfo.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabelBookInfo.setText("<html>You are managing Books. \n<br>Make sure you know what you are performing. \n<br>From here, you can:\n<br>- Search for books by id, title and first author\n<br>- Add new books\n<br>- Delete book by id\n<br>- Update book information</html>");

        javax.swing.GroupLayout jPanelBookLayout = new javax.swing.GroupLayout(jPanelBook);
        jPanelBook.setLayout(jPanelBookLayout);
        jPanelBookLayout.setHorizontalGroup(
            jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelBookLayout.createSequentialGroup()
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextFieldBookID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jTextFieldBookQuantity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldBookAvailable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBookLayout.createSequentialGroup()
                        .addComponent(jButtonBookAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBookUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBookDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonBookClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonBookSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBookInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelBookLayout.setVerticalGroup(
            jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBookLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelBookLayout.createSequentialGroup()
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBookID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBookQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBookAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonBookSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonBookClearFields)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonBookAdd)
                            .addComponent(jButtonBookDelete)
                            .addComponent(jButtonBookUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelBookInfo)))
                .addContainerGap())
        );

        jPanelReader.setBackground(new java.awt.Color(255, 255, 255));

        jTableLib1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTableLib1.setForeground(new java.awt.Color(0, 18, 91));
        jTableLib1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Title", "Fisrt author", "Quantity", "Available"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableLib1.setGridColor(new java.awt.Color(0, 18, 91));
        jTableLib1.setSelectionBackground(new java.awt.Color(0, 18, 91));
        jScrollPane2.setViewportView(jTableLib1);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 18, 91));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("ID:");

        jTextFieldReaderID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldReaderID.setForeground(new java.awt.Color(0, 18, 91));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 18, 91));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("First name:");

        jTextFieldReaderFname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldReaderFname.setForeground(new java.awt.Color(0, 18, 91));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 18, 91));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Last name:");

        jTextFieldReaderLname.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldReaderLname.setForeground(new java.awt.Color(0, 18, 91));

        jButtonReaderAdd.setBackground(new java.awt.Color(0, 18, 91));
        jButtonReaderAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReaderAdd.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReaderAdd.setText("Add");
        jButtonReaderAdd.setBorder(null);
        jButtonReaderAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReaderAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaderAddActionPerformed(evt);
            }
        });

        jButtonReaderClearField.setBackground(new java.awt.Color(0, 18, 91));
        jButtonReaderClearField.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReaderClearField.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReaderClearField.setText("Clear Fields");
        jButtonReaderClearField.setBorder(null);
        jButtonReaderClearField.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReaderClearField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaderClearFieldActionPerformed(evt);
            }
        });

        jButtonReaderDelete.setBackground(new java.awt.Color(0, 18, 91));
        jButtonReaderDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReaderDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReaderDelete.setText("Delete");
        jButtonReaderDelete.setBorder(null);
        jButtonReaderDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReaderDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaderDeleteActionPerformed(evt);
            }
        });

        jButtonReaderUpdate.setBackground(new java.awt.Color(0, 18, 91));
        jButtonReaderUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReaderUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReaderUpdate.setText("Update");
        jButtonReaderUpdate.setBorder(null);
        jButtonReaderUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReaderUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaderUpdateActionPerformed(evt);
            }
        });

        jButtonReaderSearch.setBackground(new java.awt.Color(0, 18, 91));
        jButtonReaderSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonReaderSearch.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReaderSearch.setText("Search");
        jButtonReaderSearch.setBorder(null);
        jButtonReaderSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReaderSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReaderSearchActionPerformed(evt);
            }
        });

        jLabelReaderInfo.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabelReaderInfo.setText("<html>You are managing Readers.  <br>Make sure you know what you are performing.  <br>From here, you can: <br>- Search for users by id, first name and last name <br>- Add new readers <br>- Delete reader by id <br>- Update reader information</html>");

        javax.swing.GroupLayout jPanelReaderLayout = new javax.swing.GroupLayout(jPanelReader);
        jPanelReader.setLayout(jPanelReaderLayout);
        jPanelReaderLayout.setHorizontalGroup(
            jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelReaderLayout.createSequentialGroup()
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldReaderFname, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldReaderID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextFieldReaderLname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelReaderLayout.createSequentialGroup()
                        .addComponent(jButtonReaderAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReaderUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonReaderDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonReaderClearField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonReaderSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelReaderInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanelReaderLayout.setVerticalGroup(
            jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelReaderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelReaderLayout.createSequentialGroup()
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldReaderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldReaderFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldReaderLname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84)
                        .addComponent(jButtonReaderSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonReaderClearField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelReaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonReaderAdd)
                            .addComponent(jButtonReaderDelete)
                            .addComponent(jButtonReaderUpdate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelReaderInfo)))
                .addContainerGap())
        );

        jMenu1.setText("Reader");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Book");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Issue");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelReader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelReader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookAddActionPerformed

    private void jButtonBookClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookClearFieldsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookClearFieldsActionPerformed

    private void jButtonBookDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookDeleteActionPerformed

    private void jButtonBookUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookUpdateActionPerformed

    private void jButtonBookSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBookSearchActionPerformed

    private void jButtonReaderAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaderAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaderAddActionPerformed

    private void jButtonReaderClearFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaderClearFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaderClearFieldActionPerformed

    private void jButtonReaderDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaderDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaderDeleteActionPerformed

    private void jButtonReaderUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaderUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaderUpdateActionPerformed

    private void jButtonReaderSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReaderSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReaderSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBookAdd;
    private javax.swing.JButton jButtonBookClearFields;
    private javax.swing.JButton jButtonBookDelete;
    private javax.swing.JButton jButtonBookSearch;
    private javax.swing.JButton jButtonBookUpdate;
    private javax.swing.JButton jButtonReaderAdd;
    private javax.swing.JButton jButtonReaderClearField;
    private javax.swing.JButton jButtonReaderDelete;
    private javax.swing.JButton jButtonReaderSearch;
    private javax.swing.JButton jButtonReaderUpdate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBookInfo;
    private javax.swing.JLabel jLabelReaderInfo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelBook;
    private javax.swing.JPanel jPanelReader;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLib;
    private javax.swing.JTable jTableLib1;
    private javax.swing.JTextField jTextFieldBookAuthor;
    private javax.swing.JTextField jTextFieldBookAvailable;
    private javax.swing.JTextField jTextFieldBookID;
    private javax.swing.JTextField jTextFieldBookQuantity;
    private javax.swing.JTextField jTextFieldBookTitle;
    private javax.swing.JTextField jTextFieldReaderFname;
    private javax.swing.JTextField jTextFieldReaderID;
    private javax.swing.JTextField jTextFieldReaderLname;
    // End of variables declaration//GEN-END:variables
}
